---
- name: Instalar Apache en Ubuntu y desplegar página web
  hosts: all
  become: true
  tasks:

    - name: Actualizar apt cache
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Asegurar que Apache esté iniciado y habilitado
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Crear página de bienvenida personalizada
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>Apache desde Ansible</title></head>
            <body>
              <h1>Apache instalado d
